version: "3.8"
services:
  checkout:
    build:
      context: .
      dockerfile: ./services/checkout/dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./shared:/app/shared
    environment:
      - PORT=3001

  # payment:
  #   build:
  #     context: .
  #     dockerfile: ./services/payment/dockerfile
  #   ports:
  #     - "3002:3002"
  #   volumes:
  #     - ./shared:/app/shared
  #   environment:
  #     - PORT=3002
