FROM node:18-alpine as builder

WORKDIR /app

COPY services/checkout/package*.json ./
COPY services/checkout/prisma ./prisma
COPY shared ./shared
RUN npm install
RUN npm run prisma:generate

COPY . .

RUN npm run build

# -----------------------------
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app /app

EXPOSE 3000

# Executa a aplicação
CMD ["node", "dist/main.js"]
